export const API =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

// Static snapshot fallback: when the live backend is unreachable (e.g. the
// public Vercel demo with no API host), serve pre-generated JSON from
// /public/snapshot. Generated by backend/gen_snapshots.py.
let _manifest: Record<string, string> | null | undefined;

async function loadManifest(): Promise<Record<string, string> | null> {
  if (_manifest !== undefined) return _manifest ?? null;
  try {
    // 'no-cache' = always revalidate with the server (etag) so a new deploy's
    // snapshots are picked up. 'force-cache' served stale files across deploys
    // because snapshot filenames are stable (e.g. api_knockout.json).
    const r = await fetch("/snapshot/manifest.json", { cache: "no-cache" });
    _manifest = r.ok ? await r.json() : null;
  } catch {
    _manifest = null;
  }
  return _manifest ?? null;
}

async function fromSnapshot<T>(path: string): Promise<T> {
  const manifest = await loadManifest();
  if (!manifest) throw new Error("offline: no snapshot manifest");
  // Exact path+query, else degrade to the path without its query string.
  const file = manifest[path] ?? manifest[path.split("?")[0] + "?"] ??
    manifest[path.split("?")[0]];
  if (!file) throw new Error(`offline: no snapshot for ${path}`);
  const r = await fetch(`/snapshot/${file}`, { cache: "no-cache" });
  if (!r.ok) throw new Error(`offline: snapshot ${file} ${r.status}`);
  return r.json();
}

export async function api<T = any>(path: string, init?: RequestInit): Promise<T> {
  try {
    const res = await fetch(`${API}${path}`, {
      ...init,
      headers: { "Content-Type": "application/json", ...(init?.headers || {}) },
      cache: "no-store",
    });
    if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
    return res.json();
  } catch (err) {
    // Live backend down — fall back to a static snapshot for GET requests.
    if (!init?.method || init.method.toUpperCase() === "GET") {
      return fromSnapshot<T>(path);
    }
    throw err;
  }
}

export const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
export const pct0 = (x: number) => `${Math.round(x * 100)}%`;
